import { Uri, Webview } from 'vscode';
import manifest from '../../out/webview/.vite/manifest.json';

type ViteManifestEntry = {
  file?: string;
  css?: string[];
  [key: string]: unknown;
};

// The manifest is generated by `npm run build:webview` before extension typecheck/bundling.
const viteManifest = manifest as Record<string, ViteManifestEntry>;

export type ManifestItem = keyof typeof viteManifest & string;

export class Resource {
  public constructor(public readonly resource: string) {}

  public toUri(baseUri: Uri): Uri {
    return Uri.joinPath(baseUri, ...this.resource.split('/'));
  }

  public toWebviewUri(webview: Webview, baseUri: Uri): string {
    return webview.asWebviewUri(this.toUri(baseUri)).toString();
  }

  public toString(): string {
    return this.resource;
  }
}

export const Manifest = {
  entry(resource: 'webview/index.html') {
    const entry = viteManifest[resource];
    return {
      ...entry,
      css: entry?.css?.map((css) => new Resource(css)) ?? [],
      file: entry?.file ? new Resource(entry.file) : undefined
    };
  },

  keys(): string[] {
    return Object.keys(viteManifest);
  }
};
